use welfareServices
select
p.FirstName,
p.LastName,
p.EmployeeNumber,
p.LOCAL_TELEPHONE,
p.PHONE_NUMBER,
p.TELEPHONE,
p.ADDRESS,
ct.CERTIFICATE_NAME,
(select count(cc.CHILD_ID) from CHILDREN cc where cc.PEOPLE_ID=c.PEOPLE_ID)NUMBER_OF_CHILDREN,
ms.MARITAL_STATUS_NAME,
j.JOB_TITLE,
d.DEPARTMENT_NAME,
(select dd.DEPARTMENT_NAME from DEPARTMENTS dd where d.DEPARTMENT_PARENT_ID=dd.DEPARTMENT_ID)DEPARTMENT_PARENT
from 
People p
,CERTIFICATES c
,CERTIFICATE_TYPE ct
,MARITAL_STATUS ms
,JOBS j
,DEPARTMENTS d
where 
1=1
and p.PeopleID=c.PEOPLE_ID
and c.END_DATE=(select MAX(END_DATE) from CERTIFICATES ce where ce.PEOPLE_ID=p.PeopleID)
and ct.CERTIFICATE_TYPE_ID=c.CERTIFICATE_TYPE_ID
and ms.MARITAL_STATUS_ID=p.MARITAL_STATUS_ID
and j.JOB_ID=p.JOB_ID
and d.DEPARTMENT_ID=p.DEPARTMENT_ID
